config/routes.rb
Nist::Application.routes.draw do
  get "home/index"

  resources :members

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root :to => "home#index"

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :address, :city, :code, :mobile, :name, :pincode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/index.html.erb
<div class="page-header">
  <h1 class="text-center"> NIST <small></small></h1>
</div>
<div class="jumbotron">
	<a class="btn btn-primary btn-lg text-center" role="button" href="/admin" style="color: #fff;">Login To Admin</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>nist</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<!-- Latest compiled and minified JavaScript -->

	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-default navbar-static-top navbar-fixed-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">NIST</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
			<ul class="nav navbar-nav navbar-right">
			  <% if user_signed_in? %>
				<li><%= link_to current_user.email, edit_user_registration_path %></li>
				<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%= link_to "Sign up", new_user_registration_path %></li>
				<li><%= link_to "Sign in", new_user_session_path %></li>
			  <% end %>
			</ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>

      <div class="space"></div>
      
      <div class="footer navbar-fixed-bottom">
        <div class="container">
          <div class="col-lg-9">&copy; NISt , 2014.</div>
        </div>
      </div>

    </div> <!-- /container -->
  	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	
  </body>
</html>

<style type="text/css">

  .footer {
    padding: 10px;
    background-color: #E67E22;
    color: #fff;
  }

  .footer a{
    color: #fff;
    text-decoration: none;
  }

  .space{
    height: 2em;
  }

  @media (min-width: 767px) {
    .space{
      height: 3em;
    }
  }
  /* Red * /
  $bgDefault      : #e74c3c;
  $bgHighlight    : #c0392b;
  $colDefault     : #ecf0f1;
  $colHover       : #ffbbbc; /*/
  /* Green * /
  $bgDefault      : #2ecc71;
  $bgHighlight    : #27ae60;
  $colDefault     : #ecf0f1;
  $colHover       : #d1ffed; 
  /* Purple * /
  $bgDefault      : #9b59b6;
  $bgHighlight    : #8e44ad;
  $colDefault     : #ecf0f1;
  $colHover       : #ecdbff; /*/
  /* Orange */
                             /*/


  /* --- Style --- */
  .navbar-default {
    background-color: #e67e22;
    border-color: #d35400;
  }
  .navbar-default .navbar-brand {
    color: #ecf0f1;
  }
  .navbar-default .navbar-brand:hover, .navbar-default .navbar-brand:focus {
    color: #ffe6d1;
  }
  .navbar-default .navbar-nav > li > a {
    color: #ecf0f1;
  }
  .navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus {
    color: #ffe6d1;
  }
  .navbar-default .navbar-nav .active > a, .navbar-default .navbar-nav .active > a:hover, .navbar-default .navbar-nav .active > a:focus {
    color: #ffe6d1;
    background-color: #d35400;
  }
  .navbar-default .navbar-nav .open > a, .navbar-default .navbar-nav .open > a:hover, .navbar-default .navbar-nav .open > a:focus {
    color: #ffe6d1;
    background-color: #d35400;
  }
  .navbar-default .navbar-nav .open > a .caret, .navbar-default .navbar-nav .open > a:hover .caret, .navbar-default .navbar-nav .open > a:focus .caret {
    border-top-color: #ffe6d1;
    border-bottom-color: #ffe6d1;
  }
  .navbar-default .navbar-nav > .dropdown > a .caret {
    border-top-color: #ecf0f1;
    border-bottom-color: #ecf0f1;
  }
  .navbar-default .navbar-nav > .dropdown > a:hover .caret, .navbar-default .navbar-nav > .dropdown > a:focus .caret {
    border-top-color: #ffe6d1;
    border-bottom-color: #ffe6d1;
  }
  .navbar-default .navbar-toggle {
    border-color: #d35400;
  }
  .navbar-default .navbar-toggle:hover, .navbar-default .navbar-toggle:focus {
    background-color: #d35400;
  }
  .navbar-default .navbar-toggle .icon-bar {
    background-color: #ecf0f1;
  }

  @media (max-width: 767px) {
    .navbar-default .navbar-nav .open .dropdown-menu > li > a {
      color: #ecf0f1;
    }
    .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover, .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
      color: #ffe6d1;
      background-color: #d35400;
    }
    .footer{
      text-align: center;
    }
  }

</style>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :pincode %><br />
    <%= f.text_field :pincode %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>Pincode</th>
    <th>Mobile</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.code %></td>
    <td><%= member.name %></td>
    <td><%= member.address %></td>
    <td><%= member.city %></td>
    <td><%= member.pincode %></td>
    <td><%= member.mobile %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @member.code %>
</p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Address:</b>
  <%= @member.address %>
</p>

<p>
  <b>City:</b>
  <%= @member.city %>
</p>

<p>
  <b>Pincode:</b>
  <%= @member.pincode %>
</p>

<p>
  <b>Mobile:</b>
  <%= @member.mobile %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>